name: shradha_design
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+37

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.2.0
  google_fonts: any
  get_it:
 # dio_cache_interceptor: ^3.0.1
  dio: ^4.0.4
  rxdart: ^0.27.3
  firebase_core_platform_interface: 4.5.1
  permission_handler:
  intl: ^0.17.0   # date formater


 # pin_code_fields: ^5.2.0
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.2.0
  geolocator:
  geocoding:
 # multi_image_picker: ^4.8.01
  #image_picker: ^0.8.3+2

  path_provider: ^2.0.9

  photo_view: ^0.13.0


  equatable: ^2.0.3
  flutter_bloc: ^8.0.1

  flutter_multi_formatter: ^2.5.1

  device_info: ^2.0.3
  shared_preferences: any
  package_info: any

  sqflite: ^2.0.2

  persistent_bottom_nav_bar: ^4.0.2
  share: ^2.0.4
  url_launcher: ^6.0.20
  flutter_email_sender: ^5.1.0
  flutter_launch: ^0.3.0
  image_picker: any
  # cross_file: ^0.3.1+5
  #maps_launcher: ^2.0.1
  map_launcher: ^2.2.1+1
  flutter_svg:
  dotted_border:
  need_resume: ^1.0.7+1


  firebase_messaging: ^11.2.6
  firebase_core: ^1.12.0
  flutter_local_notifications: ^9.3.2
  flutter_windowmanager: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/



  fonts:
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: PoppinsSemiMedium
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: opensans
      fonts:
        - asset: assets/fonts/opensans.ttf
        - asset: assets/fonts/opensans_medium.ttf
          weight: 600

    - family: quicksand
      fonts:
        - asset: assets/fonts/quicksand.ttf
        - asset: assets/fonts/quicksand_medium.ttf
          weight: 600
        - asset: assets/fonts/quicksand_bold.ttf
          weight: 700
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_medium.ttf
          weight: 600
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700

    - family: raleway
      fonts:
        - asset: assets/fonts/raleway.ttf
        - asset: assets/fonts/raleway_medium.ttf
          weight: 600
        - asset: assets/fonts/raleway_bold.ttf
          weight : 700

    - family: rubik
      fonts:
        - asset: assets/fonts/rubik.ttf
        - asset: assets/fonts/rubik_medium.ttf
          weight: 600
        - asset: assets/fonts/rubik_bold.ttf
          weight: 700



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  #export PATH=$PATH:/Volumes/AvinashData/Work/sdk/flutter/bin